# Execute repository tests.
name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        houdini_version: [19.5]
        include:
          - python-version: 3.9
            houdini_version: 19.5

    runs-on: ubuntu-latest
    container:
      image: captainhammy/hython-runner:${{ matrix.houdini_version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Apprentice Licenses
#        uses: captainhammy/install-houdini-apprentice-license-action@v3
        uses: "./.github/actions/install-houdini-apprentice-license-action"
        with:
          client_id: ${{ secrets.SESI_CLIENT_ID }}
          client_secret_key: ${{ secrets.SESI_SECRET_KEY }}
          houdini_version: ${{ matrix.houdini_version }}

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: pypy${{ matrix.python-version }}

      - name: Install dependencies
        run: python3 -m pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
