# Execute repository tests.
name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        houdini_version: [19.5]

    runs-on: ubuntu-latest
    container:
      image: captainhammy/hython-runner:${{ matrix.houdini_version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Apprentice Licenses
        uses: captainhammy/install-houdini-apprentice-license-action@v4

        with:
          client_id: ${{ secrets.SESI_CLIENT_ID }}
          client_secret_key: ${{ secrets.SESI_SECRET_KEY }}
          houdini_version: ${{ matrix.houdini_version }}

      - name: Install dependencies
        run: python3 -m pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
